Repository airbnb/javascript, pull requests merged in 2018-05, with the labels that each got.

#1794 only one newline at the end
  packages/eslint-config-airbnb-base/rules/style.js
Labels: semver-minor: tighten rules to match guide

#1798 Add descriptions of enforced rules
  README.md
Labels: editorial

#1799 doc: fix some nits in README.md
  README.md
Labels: editorial

#1802 Remove redundant component from label-has-for
  packages/eslint-config-airbnb/rules/react-a11y.js
Labels: semver-patch: loosen/fix/document rules

#1801 [guide] Add missing code spans
  README.md
Labels: editorial

#1818 Fix link for Temporal Dead Zones
  README.md
Labels: editorial
