Repository airbnb/javascript, pull requests merged in 2018-04, with the labels that each got.

#1778 Minor addition of spaces
  README.md
Labels: editorial

#1772 avoid __mocks__ no-extraneous-dependencies check
  packages/eslint-config-airbnb-base/rules/imports.js
Labels: semver-patch: loosen/fix/document rules

#1780 fix: bad comment already had a space at the beginning
  README.md
Labels: editorial

#1784 [guide] remove references to jscs
  README.md
Labels: editorial

#1787 Replace flag images with emoji
  README.md
Labels: editorial

#1790 Add support vietnamese language version
  react/README.md
Labels: react
