Repository airbnb/javascript, pull requests merged in 2018-03, with the labels that each got.

#1749 Adds eslint config extends with only whitespace rules enabled
  packages/eslint-config-airbnb-base/README.md
  packages/eslint-config-airbnb-base/package.json
  packages/eslint-config-airbnb-base/whitespace.js
  packages/eslint-config-airbnb/README.md
  packages/eslint-config-airbnb/package.json
  packages/eslint-config-airbnb/whitespace.js
Labels: enhancement

#1756 [docs] [js] add function-paren-newline eslint reference link
  README.md
Labels: editorial

#1760 Reflect migration from mocha to jest
  README.md
Labels: editorial

#1652 Set import/extensions to ignorePackages
  packages/eslint-config-airbnb-base/rules/imports.js
Labels: semver-patch: loosen/fix/document rules

#1768 Include 'accumulator' exception for no-param-reassign
  packages/eslint-config-airbnb-base/rules/best-practices.js
Labels: semver-patch: loosen/fix/document rules

#255 Added naming conventions for UPPERCASE use cases.
  README.md
Labels: editorial

#1774 Minor spacing update
  react/README.md
Labels: editorial
