Repository airbnb/javascript, pull requests merged in 2020-10, with the labels that each got.

#2303 [guide] add eslint rule reference for `default-param-last`
  README.md
Labels: editorial

#2306 [guide] add explanation about why to use radix when using parseInt
  README.md
Labels: editorial, hacktoberfest-accepted

#2310 Better link reference to Drupal's linter
  README.md
Labels: editorial

#2315 [guide] Update reason for preferring object destructuring
  README.md
Labels: editorial, hacktoberfest-accepted

#2320 add better messages for extra restricted globals (isFinite, isNaN)
  packages/eslint-config-airbnb-base/rules/variables.js
Labels: hacktoberfest-accepted, semver-patch: loosen/fix/document rules
